"""Alembic migration script template."""

"""change_screenshot_fields_to_text

Revision ID: 4349dd93ff5e
Revises: 949e1d099391
Create Date: 2025-12-21 07:15:37.823326+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4349dd93ff5e'
down_revision: Union[str, None] = '949e1d099391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'screenshot_url_web',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('leads', 'screenshot_url_mobile',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('leads', 'recommendations_screenshot_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'recommendations_screenshot_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('leads', 'screenshot_url_mobile',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('leads', 'screenshot_url_web',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
