"""Alembic migration script template."""

"""add_pagespeed_metrics_fields

Revision ID: 92cd777534a2
Revises: 4349dd93ff5e
Create Date: 2025-12-21 09:41:12.431515+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cd777534a2'
down_revision: Union[str, None] = '4349dd93ff5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('pagespeed_metrics_mobile', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('pagespeed_metrics_desktop', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'pagespeed_metrics_desktop')
    op.drop_column('leads', 'pagespeed_metrics_mobile')
    # ### end Alembic commands ###
