"""Alembic migration script template."""

"""Initial schema

Revision ID: fc3b9350c72f
Revises: 
Create Date: 2025-12-19 20:34:20.528560+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3b9350c72f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_templates'))
    )
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_index(op.f('ix_email_templates_is_active'), 'email_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=False)
    op.create_index('ix_templates_category', 'email_templates', ['category'], unique=False)
    op.create_index('ix_templates_name_active', 'email_templates', ['name', 'is_active'], unique=False)
    op.create_index('ix_templates_usage', 'email_templates', ['usage_count'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website_speed_web', sa.Float(), nullable=True),
    sa.Column('website_speed_mobile', sa.Float(), nullable=True),
    sa.Column('accessibility_score', sa.Float(), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('best_practices_score', sa.Float(), nullable=True),
    sa.Column('screenshot_url_web', sa.String(length=512), nullable=True),
    sa.Column('screenshot_url_mobile', sa.String(length=512), nullable=True),
    sa.Column('recommendations_screenshot_url', sa.String(length=512), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('subject_line', sa.String(length=255), nullable=True),
    sa.Column('generated_mail', sa.Text(), nullable=True),
    sa.Column('mail_sent', sa.Boolean(), nullable=False),
    sa.Column('punchlines', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('accessibility_score >= 0 AND accessibility_score <= 100', name=op.f('ck_leads_ck_a11y_range')),
    sa.CheckConstraint('best_practices_score >= 0 AND best_practices_score <= 100', name=op.f('ck_leads_ck_bp_range')),
    sa.CheckConstraint('seo_score >= 0 AND seo_score <= 100', name=op.f('ck_leads_ck_seo_range')),
    sa.CheckConstraint('website_speed_mobile >= 0 AND website_speed_mobile <= 100', name=op.f('ck_leads_ck_mobile_speed_range')),
    sa.CheckConstraint('website_speed_web >= 0 AND website_speed_web <= 100', name=op.f('ck_leads_ck_web_speed_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index('ix_leads_active', 'leads', ['deleted_at'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_leads_company'), 'leads', ['company'], unique=False)
    op.create_index('ix_leads_company_website', 'leads', ['company', 'website_url'], unique=False)
    op.create_index('ix_leads_conversation_id', 'leads', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index('ix_leads_created_mail_sent', 'leads', ['created_at', 'mail_sent'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_mail_sent'), 'leads', ['mail_sent'], unique=False)
    op.create_index('ix_leads_mail_sent_web_speed', 'leads', ['mail_sent', 'website_speed_web'], unique=False)
    op.create_index(op.f('ix_leads_website_url'), 'leads', ['website_url'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.Enum('SPEED_TEST', 'PUNCHLINE_GENERATION', 'RECOMMENDATION_CAPTURE', 'MAIL_GENERATION', 'CSV_IMPORT', 'BULK_OPERATION', name='tasktype'), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_batch_id'), 'tasks', ['batch_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_lead_id'), 'tasks', ['lead_id'], unique=False)
    op.create_index('ix_tasks_lead_user', 'tasks', ['lead_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_status_created', 'tasks', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index('ix_tasks_type_status', 'tasks', ['task_type', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index('ix_users_verified', 'users', ['is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_verified', table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index('ix_tasks_type_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index('ix_tasks_status_created', table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('ix_tasks_lead_user', table_name='tasks')
    op.drop_index(op.f('ix_tasks_lead_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_batch_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_leads_website_url'), table_name='leads')
    op.drop_index('ix_leads_mail_sent_web_speed', table_name='leads')
    op.drop_index(op.f('ix_leads_mail_sent'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index('ix_leads_created_mail_sent', table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index('ix_leads_conversation_id', table_name='leads')
    op.drop_index('ix_leads_company_website', table_name='leads')
    op.drop_index(op.f('ix_leads_company'), table_name='leads')
    op.drop_index('ix_leads_active', table_name='leads', postgresql_where='deleted_at IS NULL')
    op.drop_table('leads')
    op.drop_index('ix_templates_usage', table_name='email_templates')
    op.drop_index('ix_templates_name_active', table_name='email_templates')
    op.drop_index('ix_templates_category', table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_is_active'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
